### ISSUE TITLE
página 13 primer párrafo después de la cita

### ISSUE THREAD

**Issue by munecito** [ronibandini/ContraculturaMaker#1]
Las primeras 4 o 5 líneas necesitan revisión. Hay repeticiones.

**Comment by munecito** [comment]
Pag 53 Manual. Hay dos palabras sin espacio en un comando de ejemplo.

**Comment by munecito** [comment]
Gracias por la lectura. 

Interesante la explosión de ideas y las organización. Ojalá algún día pueda acceder a alguno de los cursos, ya sea en un viaje a Argentina o de manera remota.

**Comment by ronibandini** [comment]
Voy a revisar las erratas. Gracias por la devolución.

**Comment by ronibandini** [comment]
Voy a revisar las erratas. Gracias por la devolución.

**Comment by munecito** [comment]
Hola de nuevo Roni.

Disculpa que vuelva a escribir sobre lo mismo aun cuando al final del libro explicas que fue una decision el no someter el texto a revisiones. 

Pero el parrafo de la pagina 13 aun tiene un par de lineas repetidas.

Si es intencional, una vez mas pido disculpas, pero creo que tampoco explique bien lo que me parecio problematico.

Aqui adjunto una imagen donde aparecen resaltadas las lineas y la palabra que estan repetidas.

Saludos cordiales.
![Screenshot 2024-12-29 090752](https://github.com/user-attachments/assets/bb5f0bb5-0e91-44b4-9a74-217be5bc2769)

**Comment by ronibandini** [comment]
Muchas gracias por reportarlo. Ya fue corregido.
